version: '3'

vars:
  COLOR: '\033[1;33m'
  RESET: '\033[0m'

silent: true

tasks:
  dev:
    cmds:
      - echo -e "{{.COLOR}}DEV{{.RESET}}"
      - npx next dev

  default:
    cmds:
      - task: dev
