version: '3'

vars:
  COLOR: '\033[1;33m'
  RESET: '\033[0m'

silent: true

tasks:
  start:
    cmds:
      - echo -e "{{.COLOR}}BUILD{{.RESET}}"
      - deno task start

  check:
    cmds:
      - echo -e "{{.COLOR}}CHECK{{.RESET}}"
      - deno task check

  update:
    cmds:
      - echo -e "{{.COLOR}}UPGRADE{{.RESET}}"
      - deno task update

  fmt:
    cmds:
      - echo -e "{{.COLOR}}FORMAT{{.RESET}}"
      - deno fmt

  lint:
    cmds:
      - echo -e "{{.COLOR}}LINT{{.RESET}}"
      - deno lint
  
    
  default:
    cmds:
      - task: update
      - task: lint
      - task: fmt
      - task: start